foreground #d8d8d0
background #28181b
cursor #c9d3a8
selection_background #999a6f
selection_foreground #ffffff
active_tab_foreground #ffffff
active_tab_background #c9d3a8
inactive_tab_foreground #888888
inactive_tab_background #1a1a1a
