[Interface]
# Key for ARCH LINUX
# NetShield = 2
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = mH0cQcPnH+U0aQbcSykib8gRmxtaHCJ69YZr/zhKLGg=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CH-US#3
PublicKey = xuqP9uEGryELhamLSK9IDRNhljo3lA1zL9/gS7yj2WQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.135.104.46:51820

PersistentKeepalive = 25