# =============================================================================
# hyprpaper — Wallpaper daemon
# Este archivo es regenerado por theme-switch.sh al cambiar de tema
# =============================================================================

# Preload del wallpaper activo
preload = "__HOME__/dotfiles/recursos/wallpapers/B - Red.png"

# Wallpaper para todos los monitores
wallpaper = ,"__HOME__/dotfiles/recursos/wallpapers/B - Red.png"

# Config
ipc = on
splash = false
