# =============================================================================
# hyprpaper — Wallpaper daemon
# Este archivo es regenerado por theme-switch.sh al cambiar de tema
# =============================================================================

# Preload del wallpaper activo
preload = "/home/lcampassi/dotfiles/recursos/wallpapers/B - Red.png"

# Wallpaper para todos los monitores
wallpaper = ,"/home/lcampassi/dotfiles/recursos/wallpapers/B - Red.png"

# Config
ipc = on
splash = false
