[module/pulseaudio]
type = internal/pulseaudio

; ========= VOLUMEN NORMAL =========
format-volume = <label-volume>
format-volume-padding = 1
format-volume-foreground = ${colors.foreground}

label-volume = 󰕾 %percentage%%

; ========= MUTE =========
format-muted = <label-muted>
format-muted-padding = 1
format-muted-foreground = ${colors.disabled}

label-muted =   Muted

; ========= CLICK =========
click-right = pavucontrol &
