[module/xworkspaces]
type = internal/xworkspaces

; Usa el label de Qtile (PRINCIPAL, DEV, etc)
label-active = %name%
label-occupied = %name%
label-urgent = %name%
label-empty = %name%

; === ESTADOS ===
label-active-background = ${colors.background-alt}
label-active-foreground = ${colors.primary}
label-active-underline = ${colors.primary}
label-active-padding = 1
label-active-margin = 0 2 0 0

label-occupied-padding = 1
label-occupied-margin = 0 2 0 0

label-urgent-foreground = ${colors.alert}
label-urgent-padding = 1

label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 1
label-empty-margin = 0 2 0 0

; === COMPORTAMIENTO ===
enable-click = true
enable-scroll = false
click-right = notify-send "Workspaces" "1 → PRINCIPAL\n2 → SECUNDARIO\n3 → DEV\n4 → GENERAL\n5 → EXTRAS"